# These are supported funding model platforms

github: [maxvalue, paulfuxjaeger]
patreon: publicbetamax
# open_collective: maxvalue
ko_fi: publicbetamax
# tidelift: # The account signup form doesnt work. # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Not yet approved. # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: maxvalue
# issuehunt: # Replace with a single IssueHunt username
# otechie: # Replace with a single Otechie username
custom: ['https://www.buymeacoffee.com/publicbetamax']
